sudo: required
dist: bionic
language: generic
services:
  - docker

before_script:
  - docker run --rm --privileged sfalexrog/qemu-register:v4.1.0

script:
  - mkdir ${HOME}/output
  - docker run --rm -v $(pwd):/rosbuild/src -v ${HOME}/output:/output sfalexrog/multipack:melodic

after_script:
  - ls -la ${HOME}/output
